### PR TITLE
Bug Fixes; updated to use latest Hypertrack SDK 0.7.39.

### PR DESCRIPTION
**Pull request by anshudwibhashi**
Also: Fixed all version conflicts between Firebase's dependencies and Hypertrack's dependencies.

### CODE REVIEW

**Comment by ph4t0o0o0om** [comment]
Hi I also clone this repo but I think I have a mistakes on implementing the app. I install consumer app and driver app in separate android phone i opened first the driver app and it all done it says "finding nearest rider" but when i open my consumer app there is a TOAST MESSAGE SAY'S "No cars available" what is my error? can you please help me?

**Comment by Daggie1** [comment]
That was a nice one @anshudwibhashi worked for me!!

**Comment by ph4t0o0o0om** [comment]
@Daggie1 try to run the two app in separate phone . There is no connections at all . The consumer app can't find if there is a driver available on the area even if the driver app is open.

**Comment by tulushev** [comment]
Closing, because the project was completely rewritten.

**Pull request closed without merging**
